---
- name: Add specific key
  apt_key: id={{ docker_repo_key }} keyserver=keyserver.ubuntu.com state=present

- name: Install https apt transport package
  apt: pkg=apt-transport-https state=present 

- name: Add docker repo
  apt_repository: repo='deb {{ docker_repo }} docker main' state=present

- name: Install lxc-docker package
  apt: pkg=lxc-docker state=present 
